
services:
  app:
    build: .
    container_name: subscription_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_URL=postgres://user:password@db:5432/subscriptions?sslmode=disable

  db:
    image: postgres:15
    container_name: subscription_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
